### ISSUE TITLE
Error when sending confirmation email after registration

### ISSUE THREAD

**Issue by Nicolas8aa** [Freyb/strapi-provider-email-azure#3]
When the user register on my nextjs application through the users & permissions plugin `/api/auth/local/register`, gives me a bad request 400 with this error:
```Error "message.replyTo must be of type Array." occurred in serializing the payload - undefined```

my plugin configuration is 
```javascript
...
email: {
    config: {
      provider: "strapi-provider-email-azure",
      providerOptions: {
        endpoint: env("AZURE_ENDPOINT"),
      },
      settings: {
        defaultFrom: env("FALLBACK_EMAIL"),
      },
    },
  },
...
```

**Comment by Freyb** [comment]
Hey @Nicolas8aa ,

Thanks for reaching out. I've fixed the issue, please find the updated v1.0.3
